### ISSUE TITLE
libspline

### ISSUE THREAD

**Issue by pablorodriguezotero** [mdolab/pyspline#17]
## Description
While installing in anaconda the library pyGeo it was requested to install pySpline too.
Although both installations went well, when trying to import any of both libraries I get the next error:
cannot import name 'libspline' from partially initialized module 'pyspline' (most likely due to a circular import)

I think the source of the error is located at the pySpline.py file as it is trying to do:
from . import libspline

And in the path the is no module libspline to be imported.

Any recommendation to solve this issue?

thanks for your time

**Comment by nwu63** [comment]
Installing pySpline requires Fortran compilation. Please see the documentation page for instructions.
