### ISSUE TITLE
Verification tests of ADflow Fail after successful instalation. 

### ISSUE THREAD

**Issue by pedropaulocb** [mdolab/pyspline#34]
I successfully installed the ADflow in my computer. 
However, when trying to run the verification cases with the command ($ testflo .) all the tests failed.    

I am getting this error message:  **ImportError: cannot import name 'libspline' from 'pyspline' (/usr/local/lib/python3.9/dist-packages/pyspline-1.5.0-py3.9.egg/pyspline/__init__.py)**

I also tried to run a NACA0012 case by myself and had the same message error. 

Does anyone has crossed this mistake before? 

### Code versions
- Operating System: Ubuntu 21.04
- Python: 3.9
- OpenMPI: 4.1.1
- CGNS: 4.2
- PETSc: 3.15.4

![Terminal_Print](https://user-images.githubusercontent.com/86976101/135875387-3d044377-6750-475e-9ef7-81b77d70a6cd.png)

**Comment by bernardopacini** [comment]
We have not tested the environment you have running, so we cannot confirm that the codes will work. Please try reinstalling the code with the dependencies we support. You can find these dependencies listed on our [MACH documentation](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/install3rdPartyPackages.html).
