### ISSUE TITLE
import error by using "from pyspline import Curve"!

### ISSUE THREAD

**Issue by hntter** [mdolab/pyspline#35]
Hi, My python version is 3.8. I downloaded the zip document of **pyspline** and use "python setup.py install" to install. It showed I have successfully installed pyspline. However when I import pyspline and run, it always shows an error saying 

"ImportError: cannot import name 'libspline' from partially initialized module 'pyspline' (most likely due to a circular import) (D:\Engineering Software\Python38\lib\site-packages\pyspline\__init__.py)"

Is it because the version of my phthon wrong? How can I fixed this error?

Best wishes,

Zhengyu Qu

**Comment by eirikurj** [comment]
Hi, please have a look at the documentation, [specifically the build instructions](https://mdolab-pyspline.readthedocs-hosted.com/en/latest/building.html), on how to build and install pySpline.

**Comment by hntter** [comment]
> Hi, please have a look at the documentation, [specifically the build instructions](https://mdolab-pyspline.readthedocs-hosted.com/en/latest/building.html), on how to build and install pySpline.

Thanks for your reply. I use python on windows and I have installed gfortran as complier. The error about 'libspline' is still unsolved. What else should I do to solve this error? 

Best wishes, 

Zhengyu Qu

**Comment by nwu63** [comment]
We do not support Windows.
