### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by haizhou0410** [mdolab/pyspline#64]
Hi, when i install pyspline and make, the following error occured. Could anyone help me about this? Thank you in advance!
```
Numpy Include Directory:
#------------------------------------------------------#
#------------------------------------------------------#
f2py root directory:
#------------------------------------------------------#
cp f2py_f2cmap.ref .f2py_f2cmap
f2py pyspline.pyf
make[2]: f2py: No such file or directory
make[2]: *** [Makefile:31: all] Error 127
make[2]: Leaving directory '/home/haizhou/packages/pyspline-main/src/f2py'
make[1]: *** [Makefile:36: module] Error 2
make[1]: Leaving directory '/home/haizhou/packages/pyspline-main'
make: *** [Makefile:7: default] Error 2
```

**Comment by eirikurj** [comment]
Hey, it looks like you dont have `f2py` in your path, and neither the `numpy` include directory nor `f2py` are found. Make sure you are using a supported python and `numpy` versions (see the installation on [MACH-Aero](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/?badge=latest) for details and supported versions). Also note that if you are using system python, all python executables may have `3` added, e.g., `python3, python3-config, f2py3, pip3` and you will need to update your `config/config.mk` input file to reflect that. However, while this may work just fine, for simplicity we typically avoid system python and recommend either `pyenv` or `conda` to manage the python versions and python environments/packages. They all have executable without the `3`, meaning you can use the default pyspline config files.
