### ISSUE TITLE
regression test

### ISSUE THREAD

**Issue by haizhou0410** [mdolab/pyspline#65]
Hi, what does the following line mean in regression test?
python/reg_tests
I only see reg_tests folder under pyspline-main/tests, and there are three files in that folder: ref  test_curves.py  test_surfaces.py  test_volumes.py. After I execute python test_curves.py, nothing happend.
Could you give me some tips? Thank you in advance!

**Comment by eirikurj** [comment]
Thanks for the issue. Docs are outdated and PR #66 is up addressing that.
