### ISSUE TITLE
failing to compile

### ISSUE THREAD

**Issue by benoitpaillard** [mdolab/pyspline#67]
## Description
When trying to compile pyspline as described in doc, with config/defaults/config.LINUX_GFORTRAN.mk, I'm getting an error on final import test 
`Error: /home/jony/pyspline/src/f2py/libspline.so: undefined symbol: Npy__PyLong_AsInt`

Downgrading numpy from 1.24 to 1.18 solves this issue, but then breaks pandas and scipy

### Steps to reproduce issue
```
git clone https://github.com/mdolab/pyspline.git
cd pyspline/
cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk
make
sudo pip3 install numpy==1.18
make clean
make
```

### Current behavior
`Error: /home/jony/pyspline/src/f2py/libspline.so: undefined symbol: Npy__PyLong_AsInt`

### Expected behavior
`Testing if module libspline can be imported...
Module libspline was successfully imported`

### Code versions
- Operating System: Ubuntu 20.04
- Python: 3.8

**Comment by eirikurj** [comment]
Hi, please make sure to update `config.mk` such that `PYTHON`, `PYTHON-CONFIG`, and `F2PY` are correctly configured for your python installation.

**Comment by benoitpaillard** [comment]
Hi, this was already adapted.

Upgrading from Ubuntu 20.04 to 22.04 solved the issue.

As a sidenote I've moved to Docker due to other issues with lib compilation
https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/dockerInstructions.html
