### ISSUE TITLE
Spiro Spline of Levien and optimized bezier spline in phd of levien

### ISSUE THREAD

**Issue by stefano2734** [mdolab/pyspline#74]
# Description of feature

Spiro splines are better splines than bezier. 
A method to improve bezier splines is also shown
See https://levien.com/phd/phd.html

Spiro splines are part of software Inkscape 

# Potential solution

Analyze phd of levien for better splines.
See chapter 8 and 9 and for improved bezier page 141.
https://levien.com/phd/thesis.pdf

**Comment by lamkina** [comment]
pySpline is B-Spline kernel for curves, surfaces, and volumes. It does not use Bézier curves. This is not a relevant suggestion or contribution to the code.

**Comment by stefano2734** [comment]
Perhaps Spiro-splines are better than your b-splines. 
you can analyze it, test it in Inkscape and other and you can implement it perhaps.
or you do nothing. That is also ok, with splines with equal or better quality.
