### ISSUE TITLE
Error while compiling the module

### ISSUE THREAD

**Issue by VictorAlulema** [mdolab/pyspline#8]
## Description
Considering their advanced capabilities, I intended to use **pyspline** and **pygeo** to generate the b-spline and FFD representation of a series of lifting surfaces. So, I first downloaded the source code of pyspline and followed the steps detailed here: **http://mdolab.engin.umich.edu/docs/installInstructions/installFromScratch.html**

I have tried to compile the module in a Linux workstation and also in my personal laptop; however, I have found the following error when compiling the module with **make**
Following, you can find the error, which appears when the compilation is almost done.

### Current behavior
```python
/home/victor_alulema/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
gfortran -I../../mod -fdefault-real-8 -O2 -fPIC -I./ -c libspline-f2pywrappers2.f90
gfortran -fPIC -shared fortranobject.o libsplinemodule.o libspline-f2pywrappers2.o  -fdefault-real-8 -O2 -fPIC -L../../lib -lspline  -o libspline.so
python importTest.py
Testing if module pyspline can be imported...
Error importing libspline.so
Makefile:18: recipe for target 'all' failed
make[2]: *** [all] Error 1
make[2]: Leaving directory '/mnt/d/research/packages/pyspline/src/f2py'
Makefile:32: recipe for target 'module' failed
make[1]: *** [module] Error 2
make[1]: Leaving directory '/mnt/d/research/packages/pyspline'
Makefile:7: recipe for target 'default' failed
make: *** [default] Error 2
```

### Code version (if relevant)
**Python version:** Python 3.6.9 and Python 3.5.2

**Ubuntu version** 18.4 and 16.4

I hope you could help me with the compilation. Thanks in advance.

**Comment by eirikurj** [comment]
The printout suggests that `python2.7` interpreter was invoked, not python3.
Make sure to set the correct interpreter in the config file you are using, i.e. 
```
PYTHON = python # works for py2/py3 anaconda installs. If system installs this may need to be set to python3 explicitly
PYTHON-CONFIG = python3-config # use python-config for python 2
```
needs to be set appropriately.

**Comment by VictorAlulema** [comment]
I set **python3** in the config file and everything works well. Thank you.
